"""Initial schema

Revision ID: 70dc16196398
Revises: 
Create Date: 2026-08-04 09:59:43.693810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dc16196398'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint(
        'id',
        name="pk_sellers"
    ),
    sa.UniqueConstraint(
        'name',
        name="uq_sellers_name"
    )
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(
        ['seller_id'],
        ['sellers.id'],
        name='fk_sales_seller', 
        ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint(
        'id',
        name='pk_sales'
    )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('sellers')
    op.drop_index(
        'ix_sales_seller_id',
        table_name='sales'
    )
    # ### end Alembic commands ###
